resumeme/Backend

.github/workflows/Deploy.yml, .github/workflows/PR_Test.yml
CICD Workflow 템플릿 생성입니다
아직 서버 작업은 진행하지 않았고 해당 workflow 바탕으로 설정 진행할려고 합니다
**Prefix**
=> [GMMQ-8] feat: CICD Workflow 템플릿 생성입니다

appspec.yml, scripts/deploy.sh
CD 과정에서 AWS CodeDeploy 설정 파일 추가 시 누락 된 appspec.yml 파일 추가했습니다
**Prefix**
=> [GMMQ-8] feat: codeDeploy 설정 파일 추가

src/main/java/org/devcourse/global/advice/exception/ErrorResponse.java
error response dto 추가
custom exception 추가할 시 handler 적용 하겠습니다
**Prefix**
=> [GMMQ-32 ] feat: error response dto 추가

src/main/java/org/devcourse/resumeme/global/advice/exception/ErrorResponse.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/WebConfig.java, src/main/resources/application.yaml, src/main/resources/application.yml
application.yml, global 패키지 중복 수정하였습니다
**Prefix**
=> [GMMQ-71] feat: 중복 파일 제거

src/main/java/org/devcourse/resumeme/global/advice/exception/CustomException.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ErrorResponse.java
custom exception 추가
개발 진행하면서 상속받아 예외 추가하시면 됩니다
**Prefix**
=> [GMMQ-95] feat: custom exception 추가

src/main/java/org/devcourse/resumeme/common/domain/Position.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventStatus.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/resources/application.yml
=> feat: 이력서 첨삭 이벤트 도메인 추출

src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/domain/metor/Mentor.java, src/main/java/org/devcourse/resumeme/domain/user/BasicInfo.java, src/main/java/org/devcourse/resumeme/domain/user/Provider.java, src/main/java/org/devcourse/resumeme/domain/user/Role.java
- 멘토, 멘티 도메인 생성 (클래스 내부 Position 값은 공통 사용 값으로 대체 예정)
- 소셜로그인을 통해 사용자 정보를 받아오는 시점에 대한 이해가 아직 명확하지 않아, 
필수 입력 정보를 일단 BasicInfo 안에 모두 넣어두었습니다 (분리 예정)
**Prefix**
=> [GMMQ-45] 멘토/멘티 도메인 도출

src/main/java/org/devcourse/resumeme/common/domain/Position.java, src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/domain/resume/Training.java
이력서 도메인 클래스 추가하였습니다. (+ embedded 클래스)
**Prefix**
=> feat: Resume 도메인 클래스 추가

.github/CODEOWNERS
- 코드리뷰어 자동 등록을 위한 CODEOWNER 파일 추가
**Prefix**
=> chore: 코드리뷰어 자동 등록

.github/workflows/Deploy.yml, .github/workflows/PR_Test.yml
브랜치 명, S3 수정으로 인한 workflow 수정입니다
**Prefix**
=> docs: Github Action WorkFlow 수정

.github/workflows/Deploy.yml, build.gradle, scripts/deploy.sh, src/main/java/org/devcourse/resumeme/global/config/PropertiesConfig.java, src/main/resources/application.yml, src/test/java/org/devcourse/resumeme/common/EncryptTest.java
- dev 환경 서브모듈 제거
submodule 내부 dev에 파일 만드신 분 수정 해주세요
- 암호화 처리 하는 코드는 운영에 필요한 코드가 아니라서 테스트 라인에 만들어 뒀습니다
**Prefix**
=> feat: dev 환경 서브모듈 제거

.github/workflows/Deploy.yml, build.gradle
dev환경 MySQL 의존성 추가 및 CD step 순서 변경
**Prefix**
=> fix: dev환경 MySQL 의존성 추가 및 CD step 순서 변경

src/main/java/org/devcourse/resumeme/controller/UserController.java, src/main/java/org/devcourse/resumeme/controller/dto/PrimarySignUpInfo.java, src/main/java/org/devcourse/resumeme/domain/user/Provider.java, src/main/java/org/devcourse/resumeme/domain/user/Role.java, src/main/java/org/devcourse/resumeme/domain/user/User.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java, src/main/java/org/devcourse/resumeme/global/auth/PrincipalDetails.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/GoogleOAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/repository/UserRepository.java, src/main/java/org/devcourse/resumeme/service/UserService.java, src/main/resources/application.yml
- 소셜 로그인을 통한 서비스 회원가입 기능입니다.
- 소셜 로그인 완료 (ROLE == GUEST) -> 필수 추가정보 기입 (멘티 선택 -> ROLE == MENTEE, 멘토 선택 -> ROLE == TEMP)
- jwt 토큰 발행 관련 코드는 완성되는대로 빠르게 추가 commit 하겠습니다. 죄송합니다ㅠㅠ
Mentee, Mentor 에 들어가는 값들에 큰 차이가 없어서 클래스를 User로 통일하려고 합니다. 
멘토, 멘티 클래스는 추후 삭제하겠습니다.
**Prefix**
=> feat: 사용자는 카카오 로그인을 사용하여 가입을 할 수 있다

.github/workflows/Deploy.yml
=> fix: 오타 수정

src/main/java/org/devcourse/resumeme/common/response/IdResponse.java, src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/dto/EventCreateRequest.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/common/util/ApiDocumentUtils.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
이벤트 생성 API 생성입니다
프론트 요청으로 API 필드 변경점은 파일 변경이 많아져서 분리해서 올리겠습니다
- ControllerUnitTest : 이곳에 필요한 MockBean이랑 MVCTest 에 Controller class 추가하시면 됩니다
- ApiDocumentUtils : `document()`에서 사용하면 request, response json 이쁘게 정렬되서 나옵니다
- EventControllerTest : 추후 adoc 문서화 따로 올리겠습니다
**Prefix**
=> feat: 이벤트 생성 API 생성입니다

.github/workflows/Deploy.yml
properties.sh 생성 위치 수정했습니다
EC2에 안올라가 있어서 다시한번 경로 수정했습니다
**Prefix**
=> fix: 경로 수정

.gitignore, src/docs/asciidoc/common/eventStatus.adoc, src/docs/asciidoc/common/position.adoc, src/docs/asciidoc/index.adoc, src/main/java/org/devcourse/resumeme/common/domain/Position.java, src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java, src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java, src/test/java/org/devcourse/resumeme/common/controller/EnumController.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
Enum Code 관련 문서화 처리입니다
- EnumController, EnumControllerTest, DocumentLinkGenerator : 나중에 이곳에 계속 추가하시면 됩니다
- EventControllerTest : link 생성해서 변경해뒀습니다
**Prefix**
=> docs: Enum Code 관련 문서화 처리입니다

src/main/java/org/devcourse/resumeme/controller/dto/EventCreateRequest.java, src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTimeInfoTest.java, src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
Event 생성 request에 closeDateTime 필드 추가했습니다
[Jira 댓글](https://hongseok.atlassian.net/browse/GMMQ-57?focusedCommentId=10012)확인 부탁드려요
필드 추가되면서 같이 수정된 테스트들입니다
**Prefix**
=> feat: Event 생성 request 필드 추가

src/main/java/org/devcourse/resumeme/global/config/PropertiesConfig.java, src/main/resources/application-auth.yml
=> fix: 서브모듈 및 소셜로그인 yml 수정

src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/Duty.java, src/main/java/org/devcourse/resumeme/domain/resume/EmploymentType.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/domain/resume/Skill.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
업무 경험 등록 기능입니다.
기술 스택, 주요 업무 embedded 객체로 분리했습니다
예외로직 검증
**Prefix**
=> feat: 경력 사항 등록 기능 구현

src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/test/java/org/devcourse/resumeme/domain/resume/ProjectTest.java
프로젝트 entity로 수정하였습니다
**Prefix**
=> feat: 프로젝트 등록 기능 구현

scripts/deploy.sh
encrypt key값을 가지고 있던 properties 경로를 못불러 오던 에러
절대경로로 변경했습니다
**Prefix**
=> fix: properties 경로 절대경로로 변경

src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/event/Progress.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
이벤트 신청 도메인에 상태(참여중, 반려, 완료), 반려 사유 메시지 추가
- EventTest : 반려 도메인 메소드 테스트 추가
**Prefix**
=> feat: 이벤트 신청 도메인 필드 수정

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/dto/EventRejectRequest.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/main/java/org/devcourse/resumeme/service/vo/EventReject.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java, src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
멘토의 멘티 신청 반려 기능 구현(Controller, Service)
**Prefix**
=> feat: 멘토의 멘티 신청 반려 기능 구현

src/main/java/org/devcourse/resumeme/domain/resume/Certification.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/test/java/org/devcourse/resumeme/domain/resume/CertificationTest.java
수상 및 자격 등록 기능 구현입니다.
제목 빈값 검증 로직 테스트
**Prefix**
=> feat: 수상 및 자격 등록 기능 추가

src/main/java/org/devcourse/resumeme/domain/resume/Activity.java, src/main/java/org/devcourse/resumeme/domain/resume/Certification.java, src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/test/java/org/devcourse/resumeme/domain/resume/ActivityTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java
활동, 외국어 추가했습니다
필수 파라미터 검증
**Prefix**
=> feat: 활동, 외국어 아이템 추가

src/main/java/org/devcourse/resumeme/global/auth/OAuthTokenResponseFilter.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java, src/main/resources/application-endpoint.yml
프론트로부터 OAuth Server로 온 인가코드를 통해 Token 발급까지의 과정입니다
추후 리팩토링 진행할게요
**Prefix**
=> feat: 로그인 필터 구현

src/main/java/org/devcourse/resumeme/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/controller/dto/ResumeCreateRequest.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/service/ResumeService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ResumeTest.java
제목 저장 버튼 클릭 시 이력서 저장 기능 구현입니다
User 엔티티는 다음 pr에서 제거해도 될것 같습니다
post 요청 테스트
**Prefix**
=> feat: 이력서 저장 기능 구현

src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventStatus.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
=> feat: 이벤트 중복 생성 금지 로직 추가

src/docs/asciidoc/index.adoc
=> feat: 이력서저장 index.html 추가

.github/workflows/Deploy.yml, build.gradle, src/docs/asciidoc/index.adoc, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/resources/application-endpoint.yml
API Docs 미포함 문제 수정입니다
빠른 리뷰 부탁드려요
**Prefix**
=> fix: api docs jar 미포함 문제 수정 및 docs 작성

src/main/java/org/devcourse/resumeme/controller/MenteeController.java, src/main/java/org/devcourse/resumeme/controller/dto/RegisterInfo.java, src/main/java/org/devcourse/resumeme/controller/dto/RegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/domain/user/Role.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java, src/main/java/org/devcourse/resumeme/global/auth/model/JwtUser.java, src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java, src/main/java/org/devcourse/resumeme/repository/OAuth2InfoRedisRepository.java
- 회원가입 후 로그인 시 access, refresh 토큰 발급 및 반환
- 회원가입 시 request는 추후 프론트 로그인 담당자과 이야기 나눠서 변경될 수 있습니다
**Prefix**
=> feat: jwt 토큰 검증

src/docs/asciidoc/index.adoc, src/main/java/org/devcourse/resumeme/controller/ReviewController.java, src/main/java/org/devcourse/resumeme/controller/dto/ReviewCreateRequest.java, src/main/java/org/devcourse/resumeme/controller/dto/ReviewResponse.java, src/main/java/org/devcourse/resumeme/domain/review/Review.java, src/main/java/org/devcourse/resumeme/service/ReviewService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
리뷰 생성 관련 api 생성입니다
@beomukim 개발하다가 확인했는데 이력서랑 블락 엔티티들 관계가 반대로 선정되어있는 거 같아요
이력서 1 - M 블락 -> 이렇게 되어야할 거 같은데
이력서 M - 1 블락 -> 이렇게 되어있더라고요
확인 후 변경 부탁드려요
**Prefix**
=> feat: 리뷰 생성 관련 api 생성

src/main/java/org/devcourse/resumeme/domain/resume/Activity.java, src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/Certification.java, src/main/java/org/devcourse/resumeme/domain/resume/Duty.java, src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
이력서, block 연관관계 수정
(+ api 명세 변경 내용 반영)
**Prefix**
=> feat: 이력서 block 연관관계 수정

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/event/Progress.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java
수정된 이력서 리뷰 재요청 기능 구현입니다
@beomukim 이력서 수정 기능은 따로 추가해주시면 됩니다
**Prefix**
=> feat: 리뷰 재요청 기능 구현

src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
- 멘토 생성시 검증을 추가했습니다. 
- 멘토 도메인 테스트 코드 작성 및 검증 추가에 따른 controller 테스트 코드 수정했습니다.
- 멘토 생성시 필수값, 가능한 Role에 대한 테스트
**Prefix**
=> feat: 멘토 도메인 검증로직 추가 및 테스트 코드 작성

src/main/java/org/devcourse/resumeme/domain/admin/MentorApplicationEvent.java, src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationEventListener.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
멘토 가입 신청 저장 이벤트 생성입니다
추후 알림기능이 구현되기로 되어 있고 단순 멘토 가입 시 요청만 보내면 되기 때문에 eventListener로 분리했습니다
@ddongpuri 요청 보낼 때 ApplicationEventPublisher를 통해 MentorApplicantEvent를 보내면 됩니다
**Prefix**
=> feat: 멘토 가입 신청 저장 이벤트 생성

src/main/java/org/devcourse/resumeme/controller/CareerController.java, src/main/java/org/devcourse/resumeme/controller/dto/CareerCreateRequest.java, src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/repository/CareerRepository.java, src/main/java/org/devcourse/resumeme/service/CareerService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
=> feat: 업무경험 저장 api 구현

src/main/java/org/devcourse/resumeme/controller/ProjectController.java, src/main/java/org/devcourse/resumeme/controller/dto/ProjectCreateDto.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/repository/ProjectRepository.java, src/main/java/org/devcourse/resumeme/service/ProjectService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ProjectTest.java
=> feat: 프로젝트 저장 기능 구현

src/main/java/org/devcourse/resumeme/controller/MentorController.java, src/main/java/org/devcourse/resumeme/controller/dto/MentorInfoResponse.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
=> feat: 멘토 상세 정보 조회 기능

src/main/java/org/devcourse/resumeme/controller/CertificationController.java, src/main/java/org/devcourse/resumeme/controller/ProjectController.java, src/main/java/org/devcourse/resumeme/controller/dto/CertificationCreateRequest.java, src/main/java/org/devcourse/resumeme/controller/dto/ProjectCreateRequest.java, src/main/java/org/devcourse/resumeme/repository/CertificationRepository.java, src/main/java/org/devcourse/resumeme/service/CertificationService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java
프로젝트 저장 기능 구현입니다 (+ProjectCreateRequest 클래스명 변경)
**Prefix**
=> feat: 수상 및 자격증 저장 기능 구현

src/main/java/org/devcourse/resumeme/controller/MentorApplicationController.java, src/main/java/org/devcourse/resumeme/controller/dto/ApplicationProcessType.java, src/main/java/org/devcourse/resumeme/controller/dto/MentorApplicationResponse.java, src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java, src/main/java/org/devcourse/resumeme/service/MentorService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java
어드민 멘토 승인 요청 조회, 승인처리 기능 구현
- MentorApplicationControllerTest
**Prefix**
=> feat: 어드민 멘토 승인 요청 조회, 승인처리 기능 구현

src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
메소드 생성이 안되서 findWithMentorAll -> findAll 로 변경했습니다
**Prefix**
=> fix: 네이밍 변경

src/main/java/org/devcourse/resumeme/controller/ResultNoticeController.java, src/main/java/org/devcourse/resumeme/controller/dto/CreateResultRequest.java, src/main/java/org/devcourse/resumeme/domain/result/ResultNotice.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/repository/ResultNoticeRepository.java, src/main/java/org/devcourse/resumeme/service/ResultService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
합격 이력서 소개글 작성
이력서에 오픈 가능 여부 상태 값 필드 추가되었습니다
- ResultNoticeControllerTest
**Prefix**
=> feat: 합격 이력서 소개글 작성

src/main/java/org/devcourse/resumeme/controller/MenteeController.java, src/main/java/org/devcourse/resumeme/controller/dto/MenteeInfoUpdateRequest.java, src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/service/MenteeService.java, src/main/resources/application-endpoint.yml
- 멘토가 입력한 개인정보를 수정하는 기능입니다.
**Prefix**
=> feat: 멘티는 개인정보를 수정할 수 있다

src/main/java/org/devcourse/resumeme/controller/ActivityController.java, src/main/java/org/devcourse/resumeme/controller/ForeignLanguageController.java, src/main/java/org/devcourse/resumeme/controller/dto/ActivityRequestDto.java, src/main/java/org/devcourse/resumeme/controller/dto/ForeignLanguageRequestDto.java, src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java, src/main/java/org/devcourse/resumeme/repository/ActivityRepository.java, src/main/java/org/devcourse/resumeme/repository/ForeignLanguageRepository.java, src/main/java/org/devcourse/resumeme/service/ActivityService.java, src/main/java/org/devcourse/resumeme/service/ForeignLanguageService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java
활동 및 외국어 저장 기능 구현입니다
파일이 조금 많아요
**Prefix**
=> feat: 활동 및 외국어 저장 기능 구현

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/ReviewController.java, src/main/java/org/devcourse/resumeme/global/config/EndpointProperties.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/authorization/AuthorizationResolver.java, src/main/java/org/devcourse/resumeme/global/config/authorization/OnlyOwn.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/repository/ResumeRepository.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
endpoint 동적 권한 처리 기능 구현
AuthorizationResolver.resolve 를 통해서 해당 사용자가 접근한 resource가 자신의 것이 맞는지  repository에서 확인합니다
endpoint 에 대해서는 다같이 정리하는 시간도 가져보는 것도? 좋을 거 같네요
**Prefix**
=> feat: endpoint 동적 권한 처리 기능 구현

src/main/java/org/devcourse/resumeme/controller/ResultNoticeController.java, src/main/java/org/devcourse/resumeme/controller/dto/ResultsResponse.java, src/main/java/org/devcourse/resumeme/domain/result/ResultNotice.java, src/main/java/org/devcourse/resumeme/repository/ResultNoticeRepository.java, src/main/java/org/devcourse/resumeme/service/ResultService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java
합격 이력서 페이징 조회 처리입니다
**Prefix**
=> feat: 합격 이력서 페이징 조회

src/main/java/org/devcourse/resumeme/controller/TrainingController.java, src/main/java/org/devcourse/resumeme/controller/dto/ProjectCreateRequest.java, src/main/java/org/devcourse/resumeme/controller/dto/TrainingCreateRequest.java, src/main/java/org/devcourse/resumeme/domain/resume/Training.java, src/main/java/org/devcourse/resumeme/repository/TrainingRepository.java, src/main/java/org/devcourse/resumeme/service/TrainingService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/TrainingControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/TrainingTest.java
=> feat: 교육사항 저장 기능 구현

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/dto/EventsResponse.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java
이벤트 전체 조회 api 구현
- EventControllerTest
**Prefix**
=> feat: 이벤트 전체 조회 api 구현

src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/model/OAuth2TempInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationEventPublisher.java, src/main/java/org/devcourse/resumeme/service/MentorService.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
- 멘토로 회원가입시 어드민에 멘토 승인 요청이 보내지는 기능 구현
- 멘토가 이미 ROLE_MENTOR일 경우 이벤트 발생 불가
- 테스트 코드 변경 사항은 무시해주세요..!!
**Prefix**
=> feat: 어드민에 멘토 승인 요청하기 기능 구현

src/docs/asciidoc/all.adoc
이력서 저장 index.html 추가입니다
**Prefix**
=> docs: 이력서 저장 index.html 추가

src/main/java/org/devcourse/resumeme/global/auth/authorization/AuthorizationResolver.java, src/main/java/org/devcourse/resumeme/global/auth/authorization/OnlyOwn.java, src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2FailureHandler.java, src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2SuccessHandler.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java, src/main/java/org/devcourse/resumeme/global/config/properties/EndpointProperties.java
package 구조 변경
이 부분도 conflict 우려가 있으니 이전 pr과 같이 닫겠습니다
**Prefix**
=> chore: package 구조 변경

src/docs/asciidoc/admin.adoc, src/docs/asciidoc/all.adoc, src/docs/asciidoc/common/blockType.adoc, src/docs/asciidoc/common/progress.adoc, src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/controller/ReviewController.java, src/main/java/org/devcourse/resumeme/controller/dto/ReviewResponse.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/resume/BlockType.java, src/main/java/org/devcourse/resumeme/repository/ReviewRepository.java, src/main/java/org/devcourse/resumeme/service/ReviewService.java, src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java, src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java, src/test/java/org/devcourse/resumeme/common/controller/EnumController.java, src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java
이력서에 작성된 리뷰 전체 조회기능입니다
금일 멘토님 피드백 : adoc 파일에 테스트 완료 후 snippet 등록하기
우선 이번 pr에 밀린 docs 다 올려뒀습니다
adoc파일 5개, 테스트 파일 4개입니다
- DocumentLinkGenerator, EnumControllerTest, EnumController : Enum값 문서화 처리 용
- ReviewControllerTest
**Prefix**
=> feat: 이력서에 작성된 리뷰 전체 조회

src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java, src/test/java/org/devcourse/resumeme/controller/TrainingControllerTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java, src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java, src/test/java/org/devcourse/resumeme/domain/mentee/MenteeTest.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ForeignLanguageTest.java, src/test/java/org/devcourse/resumeme/domain/resume/ProjectTest.java, src/test/java/org/devcourse/resumeme/domain/resume/TrainingTest.java, src/test/java/org/devcourse/resumeme/domain/review/ReviewTest.java, src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
- 멘티 도메인 검증 추가하고, 테스트 코드 작성했습니다.
- Mentee, Mentor 클래스와 MenteeTest 만 봐주시면 될 것 같습니다.
- 다른 부분들은 멘토/멘티 도메인 검증로직 추가로 인한 변경사항입니다!
- merge 전 commit 정리하겠습니다
**Prefix**
=> feat: 멘티 도메인 검증로직 추가 및 테스트코드 작성

src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthAuthenticationToken.java, src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenProvider.java, src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenResolver.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
OAuthTokenResponseFilter -> ProviderManager -> OAuthTokenProvider -> OAuth2CustomUserService, OAuthTokenResolver
순서로 구조 리팩토링입니다
**Prefix**
=> refactor: OAuthTokenResponseFilter 리팩토링

src/docs/asciidoc/all.adoc, src/docs/asciidoc/common/provider.adoc, src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java, src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java, src/test/java/org/devcourse/resumeme/common/controller/EnumController.java, src/test/java/org/devcourse/resumeme/global/auth/filter/AuthFilterTestController.java, src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
프론트로부터 받은 code -> token받아오기 필터 테스트 작성입니다
OAuthTokenResponseFilter : http method post로 지정
ControllerUnitTest, AuthFilterTestController : 필터용 임의의 컨트롤러 추가
**Prefix**
=> feat: 프론트로부터 받은 code -> token받아오기 필터 테스트

src/docs/asciidoc/resume.adoc
API 명세 이력서 테이블 추가입니다
전 pr에 추가했어야 하는데 빠트려서 하나만 추가할게요
**Prefix**
=> docs: 이력서 table 추가

src/docs/asciidoc/index.adoc, src/docs/asciidoc/reference.adoc, src/main/java/org/devcourse/resumeme/common/util/Validator.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java, src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/event/exception/EventException.java, src/main/java/org/devcourse/resumeme/domain/review/Review.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationEventPublisher.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java, src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java, src/test/java/org/devcourse/resumeme/common/controller/EnumController.java, src/test/java/org/devcourse/resumeme/domain/mentee/MenteeTest.java, src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
=> refactor: exception code로 변환

src/main/java/org/devcourse/resumeme/global/advice/ExceptionControllerAdvice.java
controller advice 추가
**Prefix**
=> feat: controller advice 추가

src/docs/asciidoc/resume.adoc, src/main/java/org/devcourse/resumeme/controller/CareerController.java, src/main/java/org/devcourse/resumeme/controller/ProjectController.java, src/main/java/org/devcourse/resumeme/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/service/ProjectService.java, src/test/java/org/devcourse/resumeme/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ProjectControllerTest.java
프로젝트 조회 api 구현입니다
조회 url, 반환 타입 수정되었습니다
**Prefix**
=> feat: 프로젝트 조회 api 구현

src/docs/asciidoc/resume.adoc, src/main/java/org/devcourse/resumeme/controller/CertificationController.java, src/main/java/org/devcourse/resumeme/controller/dto/CertificationCreateRequest.java, src/main/java/org/devcourse/resumeme/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/domain/resume/Certification.java, src/test/java/org/devcourse/resumeme/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/domain/resume/CertificationTest.java
수상 및 자격증 조회 api 구현입니다
**Prefix**
=> feat: 수상 및 자격증 조회 api 구현

src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java, src/main/resources/application.yml, src/test/java/org/devcourse/resumeme/global/auth/token/JwtServiceTest.java
- 토큰 발급 및 검증 테스트
- application-auth.yml redirect-uri 변경
**Prefix**
=> test: JwtService 테스트

src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java, src/main/java/org/devcourse/resumeme/global/config/WebConfig.java
=> fix: cors 수정

src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
=> fix: 로컬 주소 추가

src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ResultNoticeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ReviewControllerTest.java, src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
=> test: 테스트코드 리팩토링

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/controller/dto/MenteeInfoResponse.java, src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java
- 실명(realName), 닉네임(nickname) 필드 추가
- 멘토, 멘티 정보 수정 항목 adoc 위치 이동
**Prefix**
=> feat: 멘티 정보 조회 response 수정

src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenProvider.java, src/main/java/org/devcourse/resumeme/global/auth/filter/resolver/OAuthTokenResolver.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java, src/main/resources/application.yml, src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java
ExceptionHandlerFilter 추가입니다
ExceptionHandlerFilter -> LogoutFilter -> JwtAuthorizationFilter -> OAuthTokenResponseFilter 순서로 진행되고 뒤에 필터들에서 발생한 에러 처리용입니다
일단은 최상위 Exception으로 받게 해뒀고 진행하면서 예외 로그 보면서 세분화할 예정입니다
**Prefix**
=> feat: ExceptionHandlerFilter 추가

src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/resources/application.yml
sendError -> setStatus, redis 설정 추가
**Prefix**
=> fix: sendError -> setStatus, redis 설정 추가

src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilter.java
=> fix: 토큰 요청 두번 나가는 오류 수정

src/main/java/org/devcourse/resumeme/controller/MenteeController.java, src/main/java/org/devcourse/resumeme/controller/MentorController.java, src/main/java/org/devcourse/resumeme/global/advice/ExceptionControllerAdvice.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/repository/MenteeRepository.java, src/main/java/org/devcourse/resumeme/repository/MentorRepository.java, src/main/java/org/devcourse/resumeme/service/MenteeService.java, src/main/java/org/devcourse/resumeme/service/MentorService.java, src/main/java/org/devcourse/resumeme/service/OAuth2InfoRedisService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java
- LazyInitializationException 해결
- RedisService 생성
- 누락 어노테이션 추가
**Prefix**
=> fix: 멘토, 멘티 조회 에러 해결 및 리팩토링

src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
=> fix: cors 전부 오픈

src/main/java/org/devcourse/resumeme/global/config/SecurityServiceConfig.java
credentials false 변경
**Prefix**
=> fix: credentials false 변경

src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java
- ROLE_MENTEE 가 고정 역할로 되어있던 문제 해결
**Prefix**
=> fix: ROLE 고정 문제 수정

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/controller/dto/ResumeInfoRequest.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java, src/main/java/org/devcourse/resumeme/service/ResumeService.java, src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
이력서 직무, 스킬셋, 자기소개 추가입니다
**Prefix**
=> feat: 이력서 직무, 스킬셋, 자기소개 추가

src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java
=> fix: 403 원인 수정

build.gradle, src/test/java/org/devcourse/resumeme/common/config/RedisContainerInitializer.java, src/test/java/org/devcourse/resumeme/common/config/RedisRepositoryConfig.java, src/test/java/org/devcourse/resumeme/repository/OAuth2InfoRedisRepositoryTest.java
=> test: 테스트 컨테이너 적용

src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
skills, duty 빈값 검증 제거입니다
**Prefix**
=> feat: skills, duty 빈값 검증 제거

src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
=> fix: 테이블 명 수정

src/main/java/org/devcourse/resumeme/controller/CommentController.java, src/test/java/org/devcourse/resumeme/controller/CommentControllerTest.java
리뷰 반환값 타입 List -> Map으로 변경
**Prefix**
=> feat: 리뷰 반환값 타입 변경

src/main/java/org/devcourse/resumeme/domain/resume/CareerPeriod.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/domain/resume/CareerTest.java
시작일 종료일 검증 로직 수정입니다
**Prefix**
=> fix: 시작일 종료일 검증 로직 수정

src/main/java/org/devcourse/resumeme/domain/resume/Career.java
duty fetch type 수정입니다
**Prefix**
=> feat: duty fetch type 수정

src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/ResumeInfo.java
collectionTable fetch type 수정입니다
**Prefix**
=> feat: collectionTable fetch type 수정

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/controller/ActivityController.java, src/main/java/org/devcourse/resumeme/controller/ForeignLanguageController.java, src/main/java/org/devcourse/resumeme/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/domain/resume/Activity.java, src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java, src/test/java/org/devcourse/resumeme/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/controller/ForeignLanguageControllerTest.java
활동 및 외국어 조회 api 구현입니다
**Prefix**
=> feat: 활동 및 외국어 조회 api 구현

src/test/java/org/devcourse/resumeme/common/util/ApiDocumentUtils.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
Request-Fields api 문서 커스텀
이번 스프린트 새로 시작 시 docs먼저 최신화 하고 시작하면 좋을거 같아요
**Prefix**
=> docs: api 문서 커스텀

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/controller/dto/ResumeRequest.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/service/ResumeService.java, src/test/java/org/devcourse/resumeme/controller/ResumeControllerTest.java
이력서 제목 저장 api 구현입니다
**Prefix**
=> feat: 이력서 제목 저장 api 구현

src/main/java/org/devcourse/resumeme/global/config/web/WebConfig.java
ConfigurationProperties Scan 베이스 패키지 설정
**Prefix**
=> fix: ConfigurationProperties Scan 베이스 패키지 설정

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/LinkType.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이력서 참고링크 조회, 수정 api 구현입니다
**Prefix**
=> feat: 이력서 참고링크 api 구현

src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java, src/main/resources/application-endpoint.yml
기존에 하나의 endpoint에서 여러 권한을 설정하면 앞서 적용한 것만 매칭이 되는 에러가 있어서 hasAnyRole로 수정했습니다
**Prefix**
=> feat: endpoint 권한 설정 수정

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventsResponse.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventInfo.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/business/event/repository/EventPositionRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/EventPositionService.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
=> feat: 이벤트 조회 반환 값 추가

src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
제약조건 최신화
거의 대부분의 값이 다 들어와야해서 변경점이 크게 없네요
**Prefix**
=> docs: 제약조건 최신화

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeResponse.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/main/java/org/devcourse/resumeme/common/domain/BaseEntity.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
멘티 이력서 조회 api 구현입니다
**Prefix**
=> feat: 멘티 이력서 조회 api 구현

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/repository/MenteeToEventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/MenteeToEventService.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/test/java/org/devcourse/resumeme/business/event/service/MenteeToEventServiceTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
- 단건 이력서로 참여한 이벤트 리스트를 조회하는 기능입니다.
**Prefix**
=> feat: 이력서로 참여한 이벤트 목록 조회

src/main/java/org/devcourse/resumeme/business/resume/domain/GPADetails.java
학점 검증로직 변경
아~~~~~주 간단한 pr입니다
**Prefix**
=> feat: 학점 검증로직 변경

src/main/java/org/devcourse/resumeme/business/event/repository/MenteeToEventRepository.java
=> fix: MenteeToEventRepository 타입 오류 수정

src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
docs 이력서 필수값, 제약조건 추가입니다
**Prefix**
=> docs: 이력서 필수값, 제약조건 추가

src/main/java/org/devcourse/resumeme/global/auth/model/jwt/JwtProperties.java, src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java, src/main/resources/application-jwt.yml, src/main/resources/application.yml, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/global/auth/service/jwt/JwtServiceTest.java
- (드디어) jwt 관련 설정 분리했습니다.
- jwtServiceTest 만료된 토큰 검증 실패, 요청에서 토큰추출 실패 테스트 추가
**Prefix**
=> feat: 토큰 설정값 파일 분리

src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentor/MentorTest.java, src/test/java/org/devcourse/resumeme/business/user/service/mentor/MentorServiceTest.java
- 멘토 domain, service 테스트
- 멘토 Service 테스트 코드를 짜다가, 도메인 테스트를 추가하는게 맞을 것 같아서 추가했습니다
**Prefix**
=> test: 멘토 관련 테스트 코드 추가

src/main/resources/application-auth.yml
=> fix: redirect-uri 임시 변경

src/main/resources/application-auth.yml
=> fix: redirect-uri 재변경

src/main/resources/application-auth.yml, src/main/resources/application.yml
=> fix: dev 환경 redirect-uri 변경

src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java
- 서버에서 보내는 header 값 인식 불가 에러 해결
**Prefix**
=> fix: 헤더 설정 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ActivityController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ProjectController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/TrainingController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/advice/ComponentAdvice.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/CareerController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/certification/CertificationController.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java
런타임 시점 동적으로 request 구체 클래스 선택하도록 구현
**Prefix**
=> feat: 런타임 시점 동적으로 request 구체 클래스 선택

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentResponse.java, src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/comment/domain/CommentTest.java
component, 리뷰 연관관계 수정
기존에 이력서랑만 연관관계있던걸 component와 연관관계 추가했습니다
**Prefix**
=> feat: component, 리뷰 연관관계 수정

src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/user/controller/UserController.java, src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
- 멘토, 멘티 마이페이지 조회용 api 입니다.
- 일단 멘토, 멘티 모두 공통된 response를 반환하지만, 추후 변경될 가능성이 있습니다!
**Prefix**
=> feat: 멘토 / 멘티 마이페이지 정보 조회

src/main/java/org/devcourse/resumeme/common/domain/Field.java, src/main/java/org/devcourse/resumeme/common/domain/Position.java, src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentee/MenteeTest.java, src/test/java/org/devcourse/resumeme/common/util/DocumentLinkGenerator.java
- 프론트와 일치하지 않는 부분이 있어 값을 추가했습니다.
**Prefix**
=> feat: Postion, Field Enum 값 추가

src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java, src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java, src/main/java/org/devcourse/resumeme/business/statistics/service/StatisticsService.java, src/test/java/org/devcourse/resumeme/business/resume/service/StatisticsServiceTest.java, src/test/java/org/devcourse/resumeme/business/user/service/statistics/StatisticsServiceTest.java
이력서 합격률 계산 기능 구현입니다. 
화면이 나올지 아직 몰라서 엔드포인트 v2로 설정하였습니다. 추가되는 통계 계산 로직은 해당 클래스에 추가할 예정입니다
**Prefix**
=> feat: 이력서 합격률 계산 기능 구현

src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java, src/main/java/org/devcourse/resumeme/global/exception/TokenException.java
- 액세스 토큰이 유효하지 않을 경우 사용할 TokenException 클래스 생성
- ExceptionHandler 에 catch 문 추가
**Prefix**
=> feat: ExceptionHandler 토큰 에러 추가

build.gradle, src/main/java/org/devcourse/resumeme/business/mail/EmailInfo.java, src/main/java/org/devcourse/resumeme/business/mail/EmailType.java, src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java, src/main/java/org/devcourse/resumeme/business/mail/service/EmailService.java, src/main/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationController.java, src/main/java/org/devcourse/resumeme/global/config/web/AsyncConfig.java, src/main/resources/application-email.yml, src/main/resources/application.yml, src/main/resources/templates/eventOpen.html, src/main/resources/templates/mentorApproved.html, src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
- 단순 메일 보내기 기능 구현입니다. (전송 실패시 재전송 기능 미구현)
- 누추한 html 이해부탁드려요..
- 공통 속성을 뺀다면, 아마 html도 하나로 활용 가능할 듯 합니다
**Prefix**
=> feat: 메일 보내기 기능 구현

build.gradle, src/main/resources/templates/admin.html
어드민 페이지 초안입니다
컨트롤러와 엔드포인트 추가는 지금 있는 pr 머지되면 추가할 예정입니다
**Prefix**
=> feat: 어드민 페이지 초안 구현

src/main/java/org/devcourse/resumeme/business/resume/domain/PassInfo.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/repository/PassInfoRepository.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java, src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java, src/main/java/org/devcourse/resumeme/business/statistics/service/StatisticsService.java, src/test/java/org/devcourse/resumeme/business/resume/service/StatisticsServiceTest.java
기간별 합격률 계산 기능 구현입니다
합격 관련 필드 embedded 클래스로 분리하였습니다. 관련 데이터를 어떻게 저장하고 활용할지는 미지수라 마음껏 의견 남겨주세요.
**Prefix**
=> feat: 기간별 합격률 계산 기능 구현

src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java, src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java
- 리프레시 토큰 비교 로직 수정 및 로그 추가
**Prefix**
=> fix: 리프레시 토큰 비교 로직 수정 및 로그 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
pathvariable type 수정입니다
**Prefix**
=> fix: pathvariable type 수정

src/main/java/org/devcourse/resumeme/business/statistics/controller/StatisticsController.java, src/main/resources/application-endpoint.yml
=> feat: 통계 어드민 추가

src/docs/asciidoc/all.adoc, src/main/java/org/devcourse/resumeme/business/user/service/mentee/MenteeService.java, src/main/java/org/devcourse/resumeme/business/user/service/mentor/MentorService.java, src/main/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandler.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityServiceConfig.java
- Refresh Token을 삭제하여 로그아웃 처리
**Prefix**
=> feat: 로그아웃 기능 구현

src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
컴포넌트 반환 값 id 추가
테스트 id 필드 추가 6개
나중에 테스트도 하나로 통합할게요
**Prefix**
=> feat: 컴포넌트 반환 값 id 추가

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
=> feat: 이력서 삭제

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/CompleteEventRequest.java, src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
=> feat: 이력서 첨삭 완료 기능 구현

src/docs/asciidoc/all.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controllerl/dto/BasicResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
=> hotfix: 이력서 기본 정보 조회 기능 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
이력서 존재 여부 검증
이력서 작성 후에 아무런 컴포넌트도 작성을 안할 가능성이 있어 이력서 자체 조회를 한번 더 진행하도록 했습니다
**Prefix**
=> fix: 이력서 존재 여부 검증

src/docs/asciidoc/all.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/resources/org/springframework/restdocs/templates/exception-response.snippet
Exception Snippet 추가 및 endpoint 수정
`exceptionResponse(List.of(ExceptionCode.name()))` 사용하시면 됩니다
endpoint resume -> resumes 수정되었습니다
**Prefix**
=> feat: Exception Snippet 추가 및 endpoint 수정

src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java
- response role 에 이상한 값이 들어가는 오류 수정
- response 에 id 값 추가
**Prefix**
=> fix: response role 값 수정 및 id 필드 추가

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/dto/BasicResumeInfo.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
엔드포인트 권한 추가
나중에 정리한번 해야할듯 하네요
**Prefix**
=> fix: 엔드포인트 권한 추가

src/main/resources/application-endpoint.yml
=> fix: 이력서 생성 엔드포인트 수정

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentResponse.java, src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java, src/main/java/org/devcourse/resumeme/common/domain/BaseEntity.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/comment/domain/CommentTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ActivityControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CareerControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/CertificationControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ForeignLanguageControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ProjectControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/TrainingControllerTest.java
리뷰 조회 반환 값 양식 수정입니다
리뷰 내에 blocktype 제거했습니다
테스트는 blocktype에 대한 수정입니다
**Prefix**
=> feat: 리뷰 조회 반환값 수정

src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
=> hotfix: 반환 id 변경

src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
=> fix: 영속성 컴포넌트 수정

src/main/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeController.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeInfoUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeRegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/MentorController.java, src/main/java/org/devcourse/resumeme/business/user/repository/mentee/MenteeRepository.java, src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/main/resources/application-endpoint.yml
- Optional 값 NPE 뜨는 에러 수정
- 멘토/멘티 정보 update 시 권한 확인 로직 추가
**Prefix**
=> fix: optional 값 검증 로직 수정 및 update 권한 검증 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
=> fix: 반환 타입 수정

src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
- 멘토가 자신이 연 이벤트 리스트 조회하는 기능 
**Prefix**
=> feat: 멘토 마이페이지 이벤트 조회

src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
=> feat: 첨삭 수정 삭제 기능 구현

src/main/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandler.java
- return문 누락으로 인한 오류 수정
**Prefix**
=> fix: 멘티 로그아웃 성공시 return 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java
component 전체 조회 type null 수정
**Prefix**
=> fix: component 전체 조회 type null 수정

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java
component, event api doc 예외코드 추가입니다
**Prefix**
=> docs: component, event api doc 예외코드 추가

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ComponentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/test/java/org/devcourse/resumeme/business/resume/controller/LinkControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
=> feat: 외부 링크 component 분리

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
=> feat: 블럭 전체 조회 수정

src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/global/auth/filter/FilterTestController.java, src/test/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilterTest.java
JWT Token Filter Test 작성
**Prefix**
=> test: JWT Token Filter Test 작성

src/main/resources/application-endpoint.yml
=> fix: 이력서 삭제 권한 엔드포인트 수정

src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java
=> fix: skills 타입 변환

src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
resumeInfo 생성자 추가입니다
**Prefix**
=> fix: resumeInfo 생성자 추가

src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
resumeInfo getter 수정입니다
**Prefix**
=> fix: resumeInfo getter 수정

src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java
skills getter 수정입니다
**Prefix**
=> fix: skills getter 수정

src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
=> fix: 지연 초기화 에러 수정

src/docs/asciidoc/all.adoc
=> docs: 활동사항 조회 docs 추가

src/main/resources/application-endpoint.yml
=> fix: 삭제 엔드포인트 권한 추가

src/main/resources/application-endpoint.yml
=> fix: 조회 엔드포인트 권한 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java
=> fix: isTeam 조건문 변경

src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java, src/main/java/org/devcourse/resumeme/business/resume/domain/GPADetails.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ResumeInfo.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java, src/test/java/org/devcourse/resumeme/business/resume/domain/ActivityTest.java
활동사항 endDate null 체크 제거, 학점 Double로 교체, 이력서 기술스택 Set 변경 및 빈 배열 반환입니다
**Prefix**
=> fix: 에러 수정

src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
- ExceptionHandlerFilter 가 먼저 오도록 필터 순서 변경
**Prefix**
=> fix: 필터 순서 변경

src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeResponse.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이력서 리스트 조회 필드 추가, 테스트 수정입니다
**Prefix**
=> fix: 테스트 수정, dto 필드 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이력서 기본조회 수정 엔드포인트 변경입니다
**Prefix**
=> fix: 이력서 기본조회 수정 엔드포인트 변경

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
생성 시간 기준 정렬
시간 관리 정책이 달라서 baseEntity를 사용하지 않고 따로 만들었습니다
**Prefix**
=> feat: 생성 시간 기준 정렬

src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/JwtAuthorizationFilter.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/global/exception/UnAuthenticatedException.java
- 토큰 검증 완료 후 로그인이 필요할 때 403 아닌 401 반환
- 이번 주말 내에 JwtService, JwtAuthenticationFilter 리팩토링 하면서 401 에러 Exceptioncode 도 같이 다시 수정할게요..!
**Prefix**
=> fix: 401 에러 추가

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventInfoResponse.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/user/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MentorEventResponse.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
=> feat: 이벤트 전체 조회 API 분리

src/main/resources/application-endpoint.yml
=> fix: endpoint 추가

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java
=> fix: id 순서 변경

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepository.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentRepository.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java, src/test/java/org/devcourse/resumeme/business/resume/repository/CustomComponentRepositoryTest.java
Component 복사 기능 추가
CC. 리뷰어
**Prefix**
=> feat: Component 복사 기능 추가

src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/AllEventFilter.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
멘티 첨삭 리스트 조회
@ddongpuri UserEventController.all() `/mentors/mentorId/events` 멘토 마이페이지 중 이벤트 조회 용 컨트롤러 파라미터 값 변경했어요 확인 부탁해요
**Prefix**
=> feat: 멘티 첨삭 리스트 조회

src/main/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationController.java, src/main/resources/templates/mentorApprovalPage.html, src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java
=> feat: 멘토 승인 페이지 구현

src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/main/resources/application-endpoint.yml, src/main/resources/application-jwt.yml, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
- 멘토 개인정보 수정 항목 : 실명 제거, 닉네임 추가
**Prefix**
=> hotfix: 멘토 개인정보 업데이트 request 필드 수정

src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/global/config/web/WebConfig.java
스케줄링을 통한 이벤트 진행 상태 값 변경
우선 매 시간 마다 변경 하도록 설정해뒀습니다
**Prefix**
=> feat: 스케줄링을 통한 이벤트 진행 상태 값 변경

src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
- 마이페이지 이벤트 관련 조회 엔드포인트 추가
- 권한 확인 로직 추가
- 403 에러 400로 변환
**Prefix**
=> fix: 마이페이지 이벤트 조회 엔드포인트 및 권한 확인 로직 추가

README.md
readme 파일 수정
나중에 한번 더 같이 수정하시죠
**Prefix**
=> docs: readme 파일 수정

src/main/resources/application-endpoint.yml
- 멘티 개인정보 수정  엔드포인트 추가
**Prefix**
=> fix: 멘티 정보 수정 엔드포인트 추가

src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Certification.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Converter.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ForeignLanguage.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Project.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Property.java, src/main/java/org/devcourse/resumeme/business/resume/domain/ReferenceLink.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Training.java, src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java, src/main/java/org/devcourse/resumeme/business/resume/domain/career/Duty.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
Component 도메인 리팩토링
추후 커스텀 템플릿 제공하기 위해 확장성 위해 도메인 생성자 Map 객체로 변환
String 값 Enum으로 분리했습니다
**Prefix**
=> refactor: Component 도메인 리팩토링

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
=> fix: rest docs 누락 추가

src/main/resources/application-endpoint.yml
=> fix: 멘티 정보 수정 엔드포인트 수정

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeMemoRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeMemoResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이력서 메모 작성, 조회 기능 구현입니다
**Prefix**
=> feat: 이력서 메모 작성, 조회 기능 구현

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventInfoResponse.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventPageResponse.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventPosition.java, src/main/java/org/devcourse/resumeme/business/event/repository/EventPositionRepository.java, src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/EventPositionService.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/global/auth/service/authorization/AuthorizationResolver.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/business/event/service/EventPositionServiceTest.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
=> feat: 이벤트 전체 조회 페이징 추가

src/docs/asciidoc/all.adoc, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/global/auth/filter/handler/CustomLogoutHandlerTest.java
- 로그아웃 필터 테스트 코드 작성 및 api 추가
**Prefix**
=> test: CustomLogoutHandler 테스트 추가

src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java
=> fix: resume service 수정

src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
=> fix: entityGraph 수정

src/main/resources/application-endpoint.yml
=> fix: 엔드포인트 추가

src/main/resources/application-endpoint.yml
=> fix: 멘토 엔드포인트 추가

src/main/java/org/devcourse/resumeme/business/resume/domain/Activity.java, src/main/java/org/devcourse/resumeme/business/resume/domain/LocalDateUtils.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Project.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Training.java, src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java, src/main/resources/application.yml
Map value null값 fallback 구축
**Prefix**
=> fix: Map value null값 fallback 구축

src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventInfoResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/career/Career.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
멘토 아이디 추가, duty 빈배열 추가
**Prefix**
=> 멘토 아이디 추가, duty 빈배열 추가

src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java, src/main/java/org/devcourse/resumeme/global/exception/advice/ExceptionControllerAdvice.java, src/main/resources/application-endpoint.yml
- 엔드포인트 개편
- HashMap -> LinkedHashMap 변경
**Prefix**
=> fix: 엔드포인트 수정 및 자료구조 변경

build.gradle, src/main/java/org/devcourse/resumeme/business/pdf/controller/PDFController.java, src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java, src/main/resources/application-endpoint.yml
- 이력서 페이지를 캡쳐해서 pdf로 변환해서 다운로드 하는 기능
- 캡쳐 구역은 아직 조절이 필요합니다.
- 생성한 pdf 경로를 일단 내부로 해두었는데 추후 수정이 필요합니다
**Prefix**
=> feat: 이력서 pdf 생성 기능 구현

src/main/resources/application-endpoint.yml
=> chore: pdf 엔드포인트 수정

src/main/resources/application-endpoint.yml
=> fix: 엔드포인트 변경

src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java
- chromedriver 경로 수정
- 리턴값 인라인 처리
**Prefix**
=> fix: chromedriver 경로 수정 및 PDFGenerator 리팩토링

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/UserControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentee/MenteeTest.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentor/MentorTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
멘토/멘티 검증 로직 추가
- 실명 : 6자 이하의 한글
- 자기소개 : 100자 이하
- 경력사항: 300자 이하
**Prefix**
=> feat: 멘토/멘티 검증 로직 추가

src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java
=> fix: jpql 실행 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java
=> fix: duties null 체크 추가

src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
component copy 로직 변경
**Prefix**
=> fix: component copy 로직 변경

src/main/java/org/devcourse/resumeme/business/resume/domain/career/Duty.java
duty component 변환 수정
**Prefix**
=> fix: duty component 변환 수정

src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
=> fix: 이력서 컴포넌트 복사 로직 수정

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/java/org/devcourse/resumeme/business/resume/controller/SnapshotController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Snapshot.java, src/main/java/org/devcourse/resumeme/business/resume/repository/SnapshotRepository.java, src/main/java/org/devcourse/resumeme/business/resume/service/SnapshotService.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java
첨삭 이후에도 원본 이력서 데이터가 변하면 안되기 때문에 스냅샷을 찍어서 관리하도록 했습니다
스냅샷 찍는 시점은 첨삭 총평 작성 직후 입니다
abstract Response 변환을 위해 type 필드 값이 추가되었습니다
**Prefix**
=> feat: 이력서 원본 데이터 스냅샷 기능

src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
=> feat: 멘티 이벤트 반환 값 추가

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이벤트, 이력서 조회 조건 추가
멘티 이벤트 경우 본인 이벤트만
이력서 조회시 완성 본 이력서만 조회 하도록 변경했습니다
**Prefix**
=> fix: 이벤트, 이력서 조회 조건 추가

src/test/java/org/devcourse/resumeme/business/resume/controller/SnapshotControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
=> docs: snapshot 문서화

src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentWithReviewResponse.java, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/OverallReviewResponse.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
총평 조회 추가
첨삭 피드백이 List로 반환되기 때문에 총평 조회 api는 따로 분리하여 생성했습니다
**Prefix**
=> feat: 총평 조회 추가

src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc
=> docs: 이벤트 관련 v2 docs 추가

src/main/java/org/devcourse/resumeme/business/pdf/controller/PDFController.java, src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java
- 이력서 pdf 요청시, 로그인 사용자와 해당 이력서 작성자의 일치 여부 확인
- chromedriver 오류 해결을 위한 optioins 설정 추가
**Prefix**
=> feat: 이력서 pdf 기능 권한 검증 로직 및 설정값 추가

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
서버 내부(127.0.0.1)에서 요청시 모든 요청 허용
**Prefix**
=> fix: 서버 내부에서 요청시 모든 요청 허용

src/main/resources/application-endpoint.yml
=> fix: 스냅샷 엔드포인트 추가

src/main/resources/application-endpoint.yml
=> fix: api endpoint 권한 추가

src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventStatus.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java
이벤트 오픈 상태 검증 변경
오픈예약, 오픈, 재오픈 상태에서는 생성 불가능하게 변경했습니다
**Prefix**
=> fix: 이벤트 오픈 상태 검증 변경

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java
이벤트 전체 조회 정렬 조건 추가
FINISH 가 가장 뒤로
나머지 중에서는 생성 날짜 순입니다
**Prefix**
=> feat: 이벤트 전체 조회 정렬 조건 추가

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventInfo.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
이벤트 제목 길이 제한 추가
추가적인 커스텀 예외 코드 추가되었습니다
**Prefix**
=> feat: 이벤트 제목 길이 제한 추가

src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventCreateRequest.java
=> feat: positions 빈값 여부 검증

src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventInfo.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventUpdateVo.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
=> feat: 이벤트 수정 API 추가

src/main/java/org/devcourse/resumeme/business/pdf/service/PDFGenerator.java
- 캡쳐 경로가 이상해서 404 뜨던 에러 해결
**Prefix**
=> fix: pdf 생성 캡처 페이지 경로 수정

src/docs/asciidoc/all.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventInfo.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventUpdateVo.java, src/main/java/org/devcourse/resumeme/business/resume/service/SnapshotService.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/business/event/controller/MenteeToEventControllerTest.java, src/test/java/org/devcourse/resumeme/business/result/controller/ResultNoticeControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerV2Test.java, src/test/java/org/devcourse/resumeme/business/resume/controller/SnapshotControllerTest.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
=> docs: Exception code 문서화

src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventInfoUpdate.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventReopen.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventUpdateVo.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
이벤트 재 오픈 API 생성
기존에 이벤트 정보 수정 API랑 같이 사용합니다
**Prefix**
=> feat: 이벤트 재 오픈 API 생성

src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/common/util/Validator.java
=> fix: 이력서 제목 빈값 검증 추가

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentResponse.java, src/main/java/org/devcourse/resumeme/business/comment/domain/Comment.java, src/main/java/org/devcourse/resumeme/business/comment/repository/CommentRepository.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java, src/test/java/org/devcourse/resumeme/business/comment/domain/CommentTest.java
복사본 이력서 수정 기능 변경입니다
**Prefix**
=> fix: comment component 연관관계 제거

src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java
복사 시점 원본 컴포넌트 아이디 주입 로직 추가입니다
**Prefix**
=> fix: 원본 컴포넌트 아이디 복사 시점 주입

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/comment/controller/dto/CommentWithReviewResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/test/java/org/devcourse/resumeme/business/comment/controller/CommentControllerTest.java
외국어 반환값 json type value 변경
**Prefix**
=> fix: 외국어 반환값 json type value 변경

src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoResponse.java
- careerContent에 자기소개가 응답으로 나가던 에러 수정
**Prefix**
=> fix: 멘토 조회 경력사항 수정

src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java
=> fix: 제목변경 수정

src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java, src/main/java/org/devcourse/resumeme/business/resume/service/ComponentService.java
컴포넌트 업데이트 시 원본 아이디 유지
**Prefix**
=> fix: 컴포넌트 업데이트 시 원본 아이디 유지

src/main/java/org/devcourse/resumeme/business/user/controller/dto/RequiredInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeRegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorRegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/domain/Role.java, src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentee/MenteeTest.java, src/test/java/org/devcourse/resumeme/business/user/domain/mentor/MentorTest.java, src/test/java/org/devcourse/resumeme/global/auth/repository/OAuth2InfoRedisRepositoryTest.java
- 'ROLE_XXX' 형태로 반환하던 role 값 변경 -> "mentee", "mentor", "pending"
**Prefix**
=> fix: 멘토/멘티 회원가입 후 role 리턴값 변경

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentSnapEvent.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentSnapEventListener.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentSnapService.java, src/main/java/org/devcourse/resumeme/business/event/domain/model/ApplimentComplete.java, src/main/java/org/devcourse/resumeme/business/event/domain/model/ApplimentReject.java, src/main/java/org/devcourse/resumeme/business/event/domain/model/ApplimentUpdate.java, src/main/java/org/devcourse/resumeme/business/event/service/MenteeToEventService.java, src/main/java/org/devcourse/resumeme/business/resume/controller/SnapshotController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CommentSnapshotResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeSnapshotResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/SnapshotResponse.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Snapshot.java, src/test/java/org/devcourse/resumeme/business/resume/controller/SnapshotControllerTest.java
피드백 반영 수정페이지에서 수정 시 componentId가 변해 완료 페이지에서 매칭을 할 수 없어 피드백도 스냅샷 제공을 하기로 했습니다
**Prefix**
=> fix: 피드백 스냅샷 추가 

src/main/java/org/devcourse/resumeme/business/event/EventCreation.java, src/main/java/org/devcourse/resumeme/business/event/EventCreationListener.java, src/main/java/org/devcourse/resumeme/business/event/EventCreationPublisher.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/business/mail/EmailType.java, src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/business/user/repository/FollowRepository.java, src/main/java/org/devcourse/resumeme/business/user/service/mentee/FollowService.java, src/main/java/org/devcourse/resumeme/business/user/service/mentee/MenteeService.java, src/main/resources/templates/eventCreated.html, src/test/java/org/devcourse/resumeme/business/event/service/EventServiceTest.java
- 이벤트 생성시 이메일 전송 기능 구현
**Prefix**
=> feat: 이벤트 등록시 해당 멘토를 팔로우하는 멘티들은 이메일 알림을 받는다

src/main/java/org/devcourse/resumeme/business/comment/service/CommentSnapEventListener.java
=> fix: endpoint 수정

src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/java/org/devcourse/resumeme/business/comment/service/CommentSnapEventListener.java
objectMapper time module 설정
**Prefix**
=> fix: objectMapper time module 설정

src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/domain/Progress.java, src/test/java/org/devcourse/resumeme/business/event/domain/EventTest.java
=> feat: 첨삭 완료 Progress 추가

src/main/resources/application-endpoint.yml
=> fix: 스냅샷 멘토 권한 오픈

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java, src/main/java/org/devcourse/resumeme/business/user/repository/FollowRepository.java, src/main/java/org/devcourse/resumeme/business/user/repository/mentor/MentorRepository.java, src/main/java/org/devcourse/resumeme/business/user/service/mentee/FollowService.java, src/main/java/org/devcourse/resumeme/business/user/service/mentor/MentorService.java, src/test/java/org/devcourse/resumeme/business/user/controller/FollowControllerTest.java
- 이벤트 상세조회 페이지에서 해당 멘토에 대한 팔로우 여부를 나타낼때 필요한 api
**Prefix**
=> feat: 특정 멘토 팔로우 여부 단건 조회 기능 구현

src/main/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationController.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/user/controller/admin/MentorApplicationControllerTest.java
=> fix: 멘토 승인 엔드포인트 변경

src/main/java/org/devcourse/resumeme/global/auth/filter/RoleConsistencyCheckFilter.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java
로그인 성공 redirect url 수정
**Prefix**
=> fix: 로그인 성공 redirect url 수정

src/main/java/org/devcourse/resumeme/business/comment/controller/CommentController.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/business/event/service/ParticipantProgressChanger.java, src/main/java/org/devcourse/resumeme/business/event/service/ParticipantProvider.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
상태값 변경, 시간 검증 로직 추가
**Prefix**
=> fix: 상태값 변경, 시간 검증 로직 추가

src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java
=> fix: 멘토 닉네임 반환 수정

src/main/resources/application-endpoint.yml
=> chore: 멘토 팔로우여부 조회 엔드포인트 추가

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/advice/ComponentAdvice.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/certification/dto/CertificationCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ComponentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/v2/ComponentCreateRequestV2.java
jackson 의존성 제거
기존에 component 생성 DTO들이 jackson 의존성이 있어 해당 부분 새로운 통합 dto만들고 제거했습니다
동적으로 값을 주입하기 때문에 request body 자체는 변경되지 않습니다
**Prefix**
=> refactor: jackson 의존성 제거

src/main/java/org/devcourse/resumeme/business/event/controller/MenteeToEventController.java, src/main/java/org/devcourse/resumeme/business/event/service/MenteeToEventService.java, src/test/java/org/devcourse/resumeme/business/event/controller/MenteeToEventControllerTest.java
=> feat: 이벤트 참여 신청 여부확인 구현

src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/business/event/service/vo/EventInfoUpdate.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java
=> fix: 즉시 오픈 이벤트 수정 조건 추가

src/main/resources/templates/mentorApprovalPage.html
멘토 승인 페이지 css 추가입니다
**Prefix**
=> feat: 멘토 승인 페이지 css 추가

src/main/java/org/devcourse/resumeme/business/event/domain/EventPosition.java, src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java
스케줄링 sql 조건 추가, enum 저장 타입 수정
**Prefix**
=> fix: 스케줄링 sql 조건 추가, enum 저장 타입 수정

src/main/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeController.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/MentorController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/global/auth/service/authorization/AuthorizationResolver.java, src/main/java/org/devcourse/resumeme/global/auth/service/authorization/OnlyOwn.java, src/main/java/org/devcourse/resumeme/global/config/security/SecurityConfig.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/Manager.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/ManagerInjector.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/Matcher.java, src/main/java/org/devcourse/resumeme/global/config/security/properties/Request.java, src/main/resources/application-endpoint.yml
endpoint 설정파일 리팩토링
mentee, mentor 관련 권한 설정도 분리했습니다
**Prefix**
=> refactor: endpoint 설정파일 리팩토링

src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java
=> fix: 엔드포인트 권한 설정 수정

src/main/java/org/devcourse/resumeme/global/config/security/properties/EndpointProperties.java
=> fix: 조건 수정

src/main/resources/application-endpoint.yml
=> fix: 엔드포인트 권한 수정

src/main/resources/application-endpoint.yml
=> fix: 엔드포인트 수정

src/main/java/org/devcourse/resumeme/global/auth/service/authorization/AuthorizationTarget.java
=> fix: 엔드포인트 관련 수정

src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java
- 멘토 활동직무 수정 안되는 문제 -> orphanRemoval = true 설정
- 이메일 본문 연결 링크 수정
**Prefix**
=> fix: orphanRemoval 설정 추가 및 이메일 링크 수정

src/main/java/org/devcourse/resumeme/business/event/controller/MenteeToEventController.java, src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/repository/MenteeToEventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/MenteeToEventService.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Resume.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
=> fix: 라스트 QA 사항 반영

src/main/java/org/devcourse/resumeme/business/userevent/controller/UserEventController.java, src/main/java/org/devcourse/resumeme/business/userevent/controller/dto/MenteeEventResponse.java, src/test/java/org/devcourse/resumeme/business/userevent/controller/UserEventControllerTest.java
=> fix: 프록시 초기화 에러 해결

src/main/java/org/devcourse/resumeme/business/user/entity/UserRepository.java
=> fix: 쿼리 수정

src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ResumeRepository.java
=> fix: 엔티티그래프 제거

src/main/java/org/devcourse/resumeme/business/user/entity/UserRepository.java
position, fields left join 추가
**Prefix**
=> fix: position, fields left join 추가

src/main/java/org/devcourse/resumeme/business/event/domain/Event.java
=> fix: 부모 삭제 전파 제거

src/main/java/org/devcourse/resumeme/business/event/domain/Event.java, src/main/java/org/devcourse/resumeme/business/event/domain/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/business/event/domain/Progress.java
반려될 경우 이력은 남겨두고 재신청 가능
**Prefix**
=> feat: 반려될 경우 이력은 남겨두고 재신청 가능

src/main/java/org/devcourse/resumeme/business/mail/service/EmailInfoGenerator.java
=> fix: 이메일 내용 링크 수정

src/main/java/org/devcourse/resumeme/business/user/entity/UserService.java
=> fix: 수정 후 저장 추가

src/main/java/org/devcourse/resumeme/global/auth/filter/ExceptionHandlerFilter.java, src/main/java/org/devcourse/resumeme/global/auth/filter/RoleConsistencyCheckFilter.java, src/main/java/org/devcourse/resumeme/global/exception/ChangeMentorRoleException.java
=> fix: 멘토 롤 검증 수정

src/main/resources/templates/eventCreated.html, src/main/resources/templates/mentorApproved.html
=> fix: 이메일 html 수정

src/main/java/org/devcourse/resumeme/global/auth/filter/RoleConsistencyCheckFilter.java
=> fix: exception 수정

src/main/java/org/devcourse/resumeme/global/auth/filter/RoleConsistencyCheckFilter.java
=> fix: 롤 검증 순서 변경

src/main/java/org/devcourse/resumeme/business/event/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/java/org/devcourse/resumeme/global/auth/service/authorization/AuthorizationResolver.java
=> fix: By 정렬조건 제거

src/main/java/org/devcourse/resumeme/business/comment/service/CommentService.java, src/main/java/org/devcourse/resumeme/business/snapshot/service/ResumeCapture.java
=> fix: snapshot 저장 조건 추가

src/main/java/org/devcourse/resumeme/business/snapshot/service/CommentCapture.java
피드백을 하나도 안달았을 경우 이력서 스냅샷 찍어오기 추가
**Prefix**
=> fix: 피드백을 하나도 안달았을 경우 이력서 스냅샷 찍어오기 추가

src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
=> fix: 조회 조건 변경
