build.gradle, src/docs/asciidoc/docinfo.html, src/docs/asciidoc/index.adoc, src/main/java/org/devcourse/resumeme/common/domain/DocsEnumType.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java, src/test/java/org/devcourse/resumeme/common/EnumControllerTest.java, src/test/java/org/devcourse/resumeme/common/controller/EnumController.java, src/test/resources/org/springframework/restdocs/templates/enum-response-fields.snippet
enum, 테스트시 사용되는 공통 코드에 대한 설정 들입니다
- docinfo.html : 특정 링크들을 팝업으로 띄우는 역할
- DocsEnumType : Enum class들 중 docs로 제공을 할 필요가 있으면 상속을 받아서 사용
- EnumController : 문서로 제공해야 할 enum들을 위한 테스트용 컨트롤러
**enum class 문서화**
1. DocsEnumType 으로 명시
2. EnumController 반환 값에 추가 (EnumDocsResponse 필드에 `Map<String, String>`타입으로 하나더 추가 하면 됩니다)
```java
public record EnumDocsResponse(Map<String, String> enumCode, // <- 기존 있던 값
Map<String, String> userType) { // <- 계속 추가
}
```
3. EnumControllerTest에서 추가
```java
document("enum-response", 
customResponseFields("userType",enumConvertFieldDescriptor(response.userType())),
customResponseFields("enumCode",enumConvertFieldDescriptor(response.enumCode())), // <- 계속 추가
)
```
**Link 생성**
1. DocumentLinkGenerator#DocUrl에 타입 추가
2. `DocumentLinkGenerator.generateLinkCode(DocUrl)` 반환 값 …
=> [GMMQ-27] feat: RestDocs 추가 설정

src/main/java/org/devcourse/resumeme/common/domain/BaseEntity.java, src/main/java/org/devcourse/resumeme/common/util/Validator.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java, src/main/java/org/devcourse/resumeme/domain/event/EventStatus.java, src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/event/exception/EventException.java, src/test/java/org/devcourse/resumeme/domain/event/EventInfoTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventPositionTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTimeInfoTest.java, src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java
프론트와 협의후 도메인 변경된 부분 수정
도메인 메소드 도출
- Event : 멘토가 여는 이력서 첨삭 이벤트
- EventInfo
- EventTimeInfo
- EventPosition : 첨삭 이벤트에 들어가는 포지션들(백, 프론트...)
- MenteeToEvent : 첨삭 이벤트에 신청한 멘티 리스트 (Event와 다대일 관계)
이전 pr 브랜치 잘못 설정해서 닫았다가 다시 pr올렸습니다
Event, EventInfo, EventPosition, EventTimeInfo, MenteeToEvent 도메인 관련 5개 테스트 파일 포합입니다
**Prefix**
=>  feat: Event 도메인 분리

src/main/java/org/devcourse/resumeme/global/config/EndpointProperties.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/resources/application-endpoint.yml
기존에는 http method가 없었던 endPoint yml 파일 양식 수정했습니다
role에 대해서도 여러 role을 설정 할 수 있도록 변경했습니다
```yaml
roles:
- matcher:
get: /api/v1/user
post:
put:
patch:
delete:
role: user, mentor 
```
**수정이유**
http method가 없어 GET `/api/v1/users`와 POST `/api/v1/users`를 구분을 할 수 없었습니다
기존에 정리해뒀던 노션에도 추후 수정해서 설명 반영해두겠습니다
**Prefix**
=> fix: endpoint 설정 http method 추가

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/dto/ApplyToEventRequest.java, src/main/java/org/devcourse/resumeme/controller/dto/ValueResponse.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/main/java/org/devcourse/resumeme/service/vo/AcceptMenteeToEvent.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/domain/event/EventTest.java, src/test/java/org/devcourse/resumeme/domain/event/MenteeToEventTest.java, src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
첨삭 이벤트 참여 기능 구현
동시성 처리는 우선 배타락을 기반으로 구현했습니다
MenteeToEvent(어떤 이벤트에 어느 멘티가 참석했는지)엔티티에 이벤트 참석 시 사용하는 이력서 아이디값이 추가가 되었습니다
ValueResponse를 만들었는데 값이 String이나 int같은거는 같이 써도 괜찮을 것 같네요
- EventControllerTest
- EventServiceTest : 총 10명을 기준으로 Lock 적용으로 인한 동시성 확인 테스트입니다
- MenteeToEventTest, EventTest는 resumeId 필드 추가로 인한 수정입니다
**Prefix**
=> feat: 첨삭 이벤트 참여 기능 구현입니다

build.gradle, src/main/java/org/devcourse/resumeme/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/domain/user/Provider.java, src/main/java/org/devcourse/resumeme/domain/user/UserCommonInfo.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUser.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2FailureHandler.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2SuccessHandler.java, src/main/java/org/devcourse/resumeme/global/auth/model/Claims.java, src/main/java/org/devcourse/resumeme/global/auth/model/OAuth2TempInfo.java, src/main/java/org/devcourse/resumeme/global/auth/token/JwtService.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/GoogleOAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/KakaoOAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java, src/main/java/org/devcourse/resumeme/global/config/RedisRepositoryConfig.java, src/main/java/org/devcourse/resumeme/global/config/SecurityConfig.java, src/main/java/org/devcourse/resumeme/repository/MenteeRepository.java, src/main/java/org/devcourse/resumeme/repository/MentorRepository.java, src/main/java/org/devcourse/resumeme/repository/OAuth2TempInfoRepository.java, src/main/java/org/devcourse/resumeme/service/MenteeService.java, src/main/resources/application.yml, src/test/resources/application.yml
- 소셜 회원가입 이력 존재 회원 
: access token, refresh token 발급 후 헤더에 넣어 반환
- 소셜 회원가입 이력 부재 회원 
: 소셜에서 얻은 회원정보 redis에 저장 후 추가 정보 입력 받아서 회원 db (멘토, 멘티) 에 최종 저장. 
access token, refresh token 발급 후 헤더에 넣어 반환
혹시 누락된 부분이 있는지 꼼꼼히 봐주시면 감사하겠습니다!!
**Prefix**
=> feat: 소셜 회원가입 이력이 없는 사용자는 필수 추가정보 입력해야한다.

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/global/advice/exception/ExceptionCode.java, src/main/java/org/devcourse/resumeme/service/ResumeService.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/support/WithMockCustomUser.java, src/test/java/org/devcourse/resumeme/support/WithMockCustomUserSecurityContextFactory.java
이벤트 신청 시 이력서 복사해서 저장하도록 기능 추가했습니다
- WithMockCustomUser : AuthenticationPrincipal을 사용하는 컨트롤러 테스트 시 사용하면 됩니다
- EventControllerTest : JwtUser 추가로 인한 수정, Resume, MentorService given절 추가
**Prefix**
=> feat: 이벤트 신청 시 이력서 복사

src/main/java/org/devcourse/resumeme/domain/resume/BlockType.java, src/main/java/org/devcourse/resumeme/domain/review/Review.java, src/main/java/org/devcourse/resumeme/repository/ReviewRepository.java, src/test/java/org/devcourse/resumeme/domain/review/ReviewTest.java
이벤트 리뷰 도메인 도출
@beomukim 리뷰 작성 시 블락단위로 리뷰를 하다보니 어떤 블락인지를 나타내기 위해 BlockType이라는 enum 값을 생성했는데 [`@Transient`](https://gmoon92.github.io/jpa/2019/09/29/what-is-the-transient-annotation-used-for-in-jpa.html)를 각 블락 Entity에 작성해둬야 할 것 같은데 제가 추가해둬도 될까요? 이번 pr에 같이 추가해서 올려둘게요
따로 DB에 저장은 되지 않고 애플리케이션 단에서만 사용하게 됩니다
나중에 이력서 조회 시 해당 type을 프론트에 같이 전달 해 주실 수 있나요?
- ReviewTest
**Prefix**
=> feat: 이벤트 리뷰 도메인 도출

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/main/java/org/devcourse/resumeme/controller/dto/EventResponse.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/repository/EventRepository.java, src/main/java/org/devcourse/resumeme/service/EventService.java, src/main/java/org/devcourse/resumeme/service/ResumeService.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/service/EventServiceTest.java
첨삭 전 후 이력서 멘토 조회
따로 상태에 맞게 나누는 것 보다는 이력서 반환 값에 첨삭 진행 상태에 대한 값으로 나타냈습니다
eventRepository에서 참여자 정보에 대해서 fetch join 추가했습니다
수정된 도메인들은 게터 추가 입니다
(Event, EventInfo, EventTimeInfo, MenteeToEvent, Resume)
게터... 
- EventServiceTest
- EventControllerTest
**Prefix**
=> feat: 첨삭 전 후 이력서 멘토 조회

src/docs/asciidoc/all.adoc, src/docs/asciidoc/index.adoc, src/docs/asciidoc/mentee.adoc, src/docs/asciidoc/mentor.adoc
rest docs 역할 별로 문서 분리
**이전**
**이후**
추후 all, mentor, mentee 별로 각각 파일에 작성하시면 됩니다
**Prefix**
=> docs: 문서 role 별로 분리

src/main/java/org/devcourse/resumeme/domain/admin/Admin.java, src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java, src/main/java/org/devcourse/resumeme/domain/admin/MentorApplicationEvent.java, src/main/java/org/devcourse/resumeme/repository/MentorApplicationRepository.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationEventListener.java, src/main/java/org/devcourse/resumeme/service/MentorApplicationService.java
어드민 관련 도메인 입니다
Admin: 이메일과 비밀번호 직접 저장 해줘서 관리
MentorApplication: 멘토 가입 신청 시 저장 해둡니다
@ddongpuri 다음 pr에 멘토 가입 신청 서비스 로직 만들예정인데 해당 메소드 사용하시면 됩니다
**Prefix**
=> feat: 어드민 도메인 구현

src/main/java/org/devcourse/resumeme/controller/MenteeController.java, src/main/java/org/devcourse/resumeme/global/auth/OAuth2CustomUserService.java, src/main/java/org/devcourse/resumeme/global/auth/model/OAuth2TempInfo.java, src/main/java/org/devcourse/resumeme/global/auth/userInfo/OAuth2UserInfo.java, src/test/java/org/devcourse/resumeme/controller/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorApplicationControllerTest.java, src/test/java/org/devcourse/resumeme/controller/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/domain/mentor/MentorTest.java
- 회원가입 완료 후에도 Redis에 소셜로그인 관련 정보가 남아있어 똑같은 정보로 재차 회원가입이 가능한 문제
-> 회원가입 완료 후 redis에 있는 정보 삭제해줌
- OAuth2TempInfo id 로 랜덤값이 할당되지 않았던 문제
-> id로 null을 넘겨줄 경우 랜덤값이 할당됨
테스트 코드는 변경사항 관련되어 수정된 것들이라 보실 필요 없습니다~
**Prefix**
=> fix: OAuth2TempInfo id값 할당 및 회원가입 후 삭제 로직 추가

src/main/java/org/devcourse/resumeme/controller/EventController.java, src/test/java/org/devcourse/resumeme/common/DocumentLinkGenerator.java, src/test/java/org/devcourse/resumeme/controller/EventControllerTest.java, src/test/java/org/devcourse/resumeme/support/WithMockCustomUser.java, src/test/java/org/devcourse/resumeme/support/WithMockCustomUserSecurityContextFactory.java
이벤트 단건 조회 역할 별 반환 값 분리
멘토일 경우에는 어떤 이력서가 들어왔는지까지 포함을 해야하고 멘티는 이벤트에 대한 기본 정보만을 가지면 되기때문에 역할 별 반환 값을 분리했고 테스트는 멘토 기준으로 작성하고 description 을 적어뒀습니다
- WithMockCustomUser, WithMockCustomUserSecurityContextFactory : 어노테이션 옵션으로 role이 추가되었습니다
**Prefix**
=> feat: 이벤트 단건 조회 역할 별 반환 값 분리

src/main/java/org/devcourse/resumeme/common/util/Validator.java, src/main/java/org/devcourse/resumeme/domain/admin/Admin.java, src/main/java/org/devcourse/resumeme/domain/admin/MentorApplication.java, src/main/java/org/devcourse/resumeme/domain/event/Event.java, src/main/java/org/devcourse/resumeme/domain/event/EventInfo.java, src/main/java/org/devcourse/resumeme/domain/event/EventPosition.java, src/main/java/org/devcourse/resumeme/domain/event/EventTimeInfo.java, src/main/java/org/devcourse/resumeme/domain/event/MenteeToEvent.java, src/main/java/org/devcourse/resumeme/domain/mentee/MenteeField.java, src/main/java/org/devcourse/resumeme/domain/mentee/MenteePosition.java, src/main/java/org/devcourse/resumeme/domain/mentee/RequiredInfo.java, src/main/java/org/devcourse/resumeme/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/domain/mentor/MentorPosition.java, src/main/java/org/devcourse/resumeme/domain/resume/Activity.java, src/main/java/org/devcourse/resumeme/domain/resume/Career.java, src/main/java/org/devcourse/resumeme/domain/resume/Certification.java, src/main/java/org/devcourse/resumeme/domain/resume/Duty.java, src/main/java/org/devcourse/resumeme/domain/resume/ForeignLanguage.java, src/main/java/org/devcourse/resumeme/domain/resume/Project.java, src/main/java/org/devcourse/resumeme/domain/resume/Resume.java, src/main/java/org/devcourse/resumeme/domain/resume/Training.java, src/main/java/org/devcourse/resumeme/domain/review/Review.java
validator 메소드명 수정
이전에 멘토님과 이야기 중 `Validator.validate()` 메소드에서 validate가 확인, 보장한다 라는 뜻을 가지고 있는데 exception 관련 처리를 하는데 메소드명이 예외를 보장한다? 라는게 뭔가 이상하다 해서 예외를 확인한다라는 뜻으로 check로 변경했습니다
혹시 다른 더 좋은 이름 생각나시면 말씀해주세요
아마 많이 conflict가 날 것 같으니 해당 pr은 다른 분들 현재 하고있는 것들 pr 올리고 닫으면 그 뒤에 바로 닫을게요
**Prefix**
=> chore: validator 메소드명 수정

src/main/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeController.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeRegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/MentorController.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorRegisterInfoRequest.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/main/java/org/devcourse/resumeme/global/auth/filter/handler/OAuth2FailureHandler.java, src/main/java/org/devcourse/resumeme/global/auth/service/jwt/JwtService.java, src/main/java/org/devcourse/resumeme/global/auth/service/jwt/Token.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/global/auth/filter/OAuthTokenResponseFilterTest.java, src/test/java/org/devcourse/resumeme/global/auth/service/jwt/JwtServiceTest.java
- 토큰 헤더 네임 수정 : "access" -> "Authorization" , "refresh" -> "Refresh-Token"
- 멘토 / 멘티 refreshToken 값 null 허용
- 테스트 변경사항은 토큰 이름뿐이라서 안보셔도 됩니다!
**Prefix**
=> feat: JwtService 로직 및 토큰 헤더 이름 수정

src/main/java/org/devcourse/resumeme/business/user/controller/dto/UserInfoResponse.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentee/dto/MenteeInfoResponse.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoResponse.java, src/main/java/org/devcourse/resumeme/business/user/domain/Role.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentor/Mentor.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentee/MenteeControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java
- 기존에 "ROLE_XXX" 형태로 넘어가던 역할 "mentor", "mentee", "pending" 으로 교체
- 멘토/멘티 일반 단건 조회의 경우 이미 역할을 알고 있어야 요청을 보낼 수 있기 때문에 response 에서 삭제
**Prefix**
=> fix: 멘토/멘티 조회 response role 값 수정 및 삭제

src/docs/asciidoc/mentor.adoc, src/main/java/org/devcourse/resumeme/business/event/controller/EventController.java, src/main/java/org/devcourse/resumeme/business/event/controller/dto/EventResponse.java, src/main/java/org/devcourse/resumeme/business/event/service/EventService.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/event/controller/EventControllerTest.java
- 이벤트 전체 조회 api 통일 : /api/v1/events
- queryParam mentorId 없을 경우 : 전체 이벤트 조회
- queryParam mentorId 있고, mentorId == 지금 로그인한 멘토 id 인 경우 : 자기가 만든 이벤트 목록 조회 + 딸린 이력서 목록
- queryParam mentorId 있는데, mentorId != 지금 로그인한 멘토 id 인 경우 : 특정 멘토가 만든 이벤트 목록들만 조회
- queryParam mentorId 있는데, 지금 로그인한 사람이 멘티인 경우 : 특정 멘토가 만든 이벤트 목록들만 조회 
**Prefix**
=> feat: 이벤트 전체 조회 api 통합

src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/ComponentResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/BasicResumeInfo.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/java/org/devcourse/resumeme/business/resume/domain/Resume.java, src/main/java/org/devcourse/resumeme/business/resume/entity/Component.java, src/main/java/org/devcourse/resumeme/business/resume/repository/ComponentCustomRepositoryImpl.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java
이력서, Component 반환 값 추가
이력서 첨삭 완료 후 수정페이지내에서 사용합니다
- 원본 이력서 아이디 : 1번
- 이벤트에 참여하기 위해 복사된 이력서 아이디 : 2번
수정 페이지에서 사용할 API
1. 2번 이력서 기본정보 조회
2. 2번 이력서 component 조회
3. 2번 이력서에 대한 피드백 조회
4. 1번 이력서 component 조회
이력서 기본 정보 조회에 원본 이력서 아이디 값을 추가했습니다
Component 조회 시 원본 Component 아이디 값을 추가했습니다
복사 된 이력서에서 원본 Component를 보여줄지 여부를 위해 피드백 반영 여부 값을 추가했습니다
**Prefix**
=> feat: 이력서, Component 반환 값 추가

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerV2.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/v2/ResumeUpdateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/domain/model/ResumeBasicInfoUpdateModel.java, src/main/java/org/devcourse/resumeme/business/resume/domain/model/ResumeMemoUpdateModel.java, src/main/java/org/devcourse/resumeme/business/resume/domain/model/ResumeTitleUpdateModel.java, src/main/java/org/devcourse/resumeme/business/resume/domain/model/ResumeUpdateModel.java, src/main/java/org/devcourse/resumeme/business/resume/service/ResumeService.java, src/main/java/org/devcourse/resumeme/business/resume/service/v2/ResumeBasicInfoUpdate.java, src/main/java/org/devcourse/resumeme/business/resume/service/v2/ResumeMemoUpdate.java, src/main/java/org/devcourse/resumeme/business/resume/service/v2/ResumeTitleUpdate.java, src/main/java/org/devcourse/resumeme/business/resume/service/v2/ResumeUpdateVo.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerTest.java, src/test/java/org/devcourse/resumeme/business/resume/controller/ResumeControllerV2Test.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java, src/test/java/org/devcourse/resumeme/common/support/NullableHttpRequestSnippet.java
이력서 업데이트 api 통합
이력서 메모 조회 개별 -> 이력서 리스트 조회 반환값에 통합
일단 v2로 지정해뒀습니다
이력서 메모는 리스트 조회시만 사용한다해서 통합했습니다
**Prefix**
=> refactor: 이력서 업데이트 api 통합

src/main/java/org/devcourse/resumeme/business/resume/controller/ComponentController.java, src/main/java/org/devcourse/resumeme/business/resume/controller/advice/ComponentAdvice.java, src/main/java/org/devcourse/resumeme/business/resume/controller/career/dto/CareerResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ActivityResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/CertificationResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ComponentCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageCreateRequest.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ForeignLanguageResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ProjectResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/ResumeLinkResponse.java, src/main/java/org/devcourse/resumeme/business/resume/controller/dto/TrainingResponse.java, src/main/java/org/devcourse/resumeme/business/resume/domain/BlockType.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/resume/controller/ComponentResponse.java, src/test/java/org/devcourse/resumeme/business/resume/controller/SnapshotControllerTest.java
Component 리팩토링
ComponentController의 getComponent접근 전에 onlyOwn을 통해 해당 이력서 아이디에 대한 접근 권한을 설정하기 때문에 이미 존재하는 리소스임을 판단한다 생각해서 resume 조회에 대한 로직 제거했습니다
**Prefix**
=> refactor: Component 리팩토링

src/main/java/org/devcourse/resumeme/business/resume/entity/Snapshot.java
resumeData column 타입 명시
기존에는 계속 `@Lob`이 tinyText로 지정이 되어서 해당 타입 Longtext로 직접 명시했습니다
**Prefix**
=> fix: resumeData column 타입 명시

src/docs/asciidoc/mentee.adoc, src/main/java/org/devcourse/resumeme/business/user/controller/FollowController.java, src/main/java/org/devcourse/resumeme/business/user/controller/dto/FollowRequest.java, src/main/java/org/devcourse/resumeme/business/user/controller/dto/FollowResponse.java, src/main/java/org/devcourse/resumeme/business/user/controller/mentor/dto/MentorInfoResponse.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Follow.java, src/main/java/org/devcourse/resumeme/business/user/domain/mentee/Mentee.java, src/main/java/org/devcourse/resumeme/business/user/repository/FollowRepository.java, src/main/java/org/devcourse/resumeme/business/user/service/mentee/FollowService.java, src/main/java/org/devcourse/resumeme/business/user/service/mentor/MentorService.java, src/main/java/org/devcourse/resumeme/global/exception/ExceptionCode.java, src/main/resources/application-endpoint.yml, src/test/java/org/devcourse/resumeme/business/user/controller/FollowControllerTest.java, src/test/java/org/devcourse/resumeme/business/user/controller/mentor/MentorControllerTest.java, src/test/java/org/devcourse/resumeme/common/ControllerUnitTest.java
- 팔로우와 멘토, 멘티 사이 연관관계 삭제 -> id 값으로 대체
- 팔로우 가능한 최대 멘토 수는 3명으로 제한
- 이전 PR과 내용은 거의 비슷하고, 연관관계는 끊었습니다.
**Prefix**
=> feat: 관심멘토 설정 기능
